INSERT INTO cuisines (name, created_at, updated_at) VALUE('African', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('American', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('British', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Cajun', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Caribbean', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Chinese', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Eastern European', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('European', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('French', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('German', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Greek', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Indian', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Irish', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Italian', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Japanese', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Jewish', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Korean', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Latin American', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Mediterranean', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Mexican', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Middle Eastern', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Nordic', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Southern', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Spanish', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Thai', NOW(), NOW());
INSERT INTO cuisines (name, created_at, updated_at) VALUE('Vietnamese', NOW(), NOW());